# Generated by Django 2.2.11 on 2020-10-16 13:08

from django.db import migrations, models
import django.db.models.deletion
import signbank.video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Descriptive name of the video.', max_length=100, verbose_name='Title')),
                ('videofile', models.FileField(help_text='Video file.', storage=signbank.video.models.GlossVideoStorage(), upload_to='', verbose_name='Video file')),
                ('posterfile', models.FileField(blank=True, default='', help_text='Still image representation of the video.', storage=signbank.video.models.GlossVideoStorage(), upload_to='posters', verbose_name='Poster file')),
                ('is_public', models.BooleanField(default=True, help_text='Is this video is public or private?', verbose_name='Public')),
                ('version', models.IntegerField(default=0, help_text="A number that represents the order of the Glossvideo's in a gloss page. Smaller number means higher priority.", verbose_name='Version')),
                ('dataset', models.ForeignKey(help_text='Dataset of a GlossVideo, derived from gloss (if any) or chosen when video was uploaded.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Dataset', verbose_name='Glossvideo dataset')),
                ('gloss', models.ForeignKey(help_text='The gloss this GlossVideo is related to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss', verbose_name='Gloss')),
            ],
            options={
                'verbose_name': 'Gloss video',
                'verbose_name_plural': 'Gloss videos',
                'ordering': ['version'],
            },
        ),
    ]
